# Site settings
title: "Kanji Takahashi | 高橋寛治"
description: "高橋 寛治 (Takahashi Kanji)のページ。長岡技術科学大学修士2年です。自然言語処理研究室で言語処理に関する研究およびツール開発を行っています。"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kanji Takahashi (髙橋 寛治)"
resume_name_ja:                 "髙橋 寛治"
resume_title:                   "About me"
resume_contact_email:
  "takahashi@jnlp.org"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kanjirz50"
  resume_twitter_url:           "http://twitter.com/kanji250tr"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kanji-takahashi-5186aa119"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  resume_eight_url:             "https://8card.net/p/34779592122"
  resume_qiita_url:             "http://qiita.com/kanjirz50"
  resume_slideshare_url:        "http://www.slideshare.net/kanjitakahashi33"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
